unzip("household_power_consumption.txt") 
col_names <- c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
data <- read.table("household_power_consumption.txt", sep = ";", skip = 66637, nrows = 2880, col.names = col_names)
data <- within(data, Date <- strptime(data$Date, format = "%d/%m/%Y"))
data$DateTime <- paste(data$Date, data$Time)
data <- data[,c(10, 3:9)]
data$DateTime<-as.POSIXlt(data$DateTime)
plot(data$DateTime,data$Global_active_power,ylab='Global Active Power (kilowatts)', xlab='', type='l')
dev.copy(png, file = "plot2.png")
dev.off()